#!/bin/sh /etc/rc.common

START=14
STOP=98
USE_PROCD=1

PROG=/usr/sbin/uartmuxd
UART_DEV=/dev/ttyS1
BAUD=115200

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" \
        -d "$UART_DEV" \
        -b "$BAUD"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    rm -f /dev/umxtty0 /dev/umxtty1 /dev/umxtty2
}
